### PR TITLE
- Migrated PlayerIOServer to .NET Standard 2.0 / .NET Core 3.1

### PR DESCRIPTION
**Pull request by Daddoon**
- Migrated PlayerIOServer to .NET Core 3.1
- [x] Tested basic functionnality on Windows (Windows 10) - SimpleRegister, with OpenPlayerIO/PlayerIOClient
- [x] Tested basic functionnality on Linux (Debian 10) - SimpleRegister, with OpenPlayerIO/PlayerIOClient

### CODE REVIEW

**Comment by miou-gh** [comment]
Thanks for the contribution!

I'll merge this as it looks good upon review. I would note however that there is a library inspired by Player.IO which was built for .NET Core [here](https://github.com/OpenPlayerIO/Venture)

The server code is pretty experimental. I have tinkered with every socket server library out there and they've all had some severe issues which would cause downtime if used in production.

**Comment by Daddoon** [comment]
@atillabyte Even tested Embedio for the server side ?

By the way, thanks also for the link, i will take a look at it too ! But it seem the other library is only the PlayerIOClient ?

I mainly want to use a PlayerIO compatible server/client, because i'm trying to release an older game of mine, and i don't want to rewrite the server logic, however, the pricing tag of the official PlayerIO seem too high, as you have bandwith / transfert cap that are then not free...

Thanks for your work, pretty well written otherwise, even if it was experimental

EDIT: Nevermind about EmbedIO, it's a WebSocket server, not a socket one !

**Comment by Daddoon** [comment]
Ha ! Additionnaly, i don't have written this in the PR here but:

- I removed the official Inferno NuGet package as it's not yet compliant to .NET Standard 2.0 officially
- I added manually a DLL in the project that i have built, then referenced in the project, of Inferno, compatible .NET Standard 2.0, from this fork & branch here: https://github.com/0xced/SecurityDriven.Inferno/tree/netatandard2.0

I don't know if the maybe related missing / changing bits from this current Inferno version are concerned by your project, see this [issue](https://github.com/sdrapkin/SecurityDriven.Inferno/issues/10).

**Comment by Daddoon** [comment]
What Socket implementation did you test ?

Or at least, did you tried the System.Net.Sockets class's available in .NET ? I don't know if this is better handled in .NET Core and/or on Linux.

Actually what was the main issue ?

Don't want to bother you, it's just if i want to do some test on my side in few days, and if i can do a PR if something improved !

**Comment by miou-gh** [comment]
I tried to integrate every open source socket server library I could find, and did a bunch of testing and found strange behaviour occurring that shouldn't ever happen - socket disconnectiosn or buffers being overfilled, latency issues when running for ectended periods of time and improper disposals leading to memory constraints.

I decided to create my own asynchronous socket server library although I haven't merged it or integrated it into this project. I was working on a creating a separate game development framework similar to Player.IO instead of inheriting all of their strangeness for 1:1 compatibility.

If others are interested in pursuing 1:1 compatibility, they're perfectly free to however. I just think it's shackling yourself down a bit too much to be worthwhile.

**Comment by Daddoon** [comment]
I think you are right, about doing your own path.

As my main goal is mainly for doing some authoritative actions on the server-side, and not really for doing real multiplayer actions, maybe your current implementation will be enough for proofing my project, maybe i will just schedule a quick service restart every day at a specific hour as it's not critical haha !

Thanks for your hints !

**Pull request merged**
